<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ZAUSV-GSAHA" failures="0" tests="78" name="Test_Suite.TestHarness_RegressionSuite" time="4362.208" errors="8" timestamp="2023-04-27T14:04:15 IST" skipped="0">
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC19_HTTP_Validate_for_Token_Auth_Settle_Error_Message" time="33.762"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC35_HTTP_Embedded_SaveCard_ES_Stripe_Validation" time="183.925">
    <error message="Unexpected result for screenshot command: com.google.common.collect.Maps$TransformedEntriesMap instance" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Unexpected result for screenshot command: com.google.common.collect.Maps$TransformedEntriesMap instance
at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:326)
at utilities.CaptureScreenshot.getScreenshot(CaptureScreenshot.java:24)
at Test_Suite.TestHarness_RegressionSuite.TC35_HTTP_Embedded_SaveCard_ES_Stripe_Validation(TestHarness_RegressionSuite.java:3107)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC35_HTTP_Embedded_SaveCard_ES_Stripe_Validation -->
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC30_SOAP_TokenRefund_ES_Stripe_Validation" time="93.895"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC30_SOAP_TokenRefund_ES_Stripe_Validation" time="48.545"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC11_HTTP_Authorise_Error_Message" time="63.474"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC04_HTTP_Tokenise_ES_Stripe_Validation" time="27.481"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC10_HTTP_Authorise_ES_Stripe_Validation" time="27.618"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC12_HTTP_AuthSettle_ES_Stripe_Validation" time="84.709"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC02_HTTP_Tokenise_Request_Response" time="30.370"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC17_HTTP_Validate_for_Token_Settle_Error_Message" time="33.626"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC13_HTTP_AuthSettle_Error_Message" time="26.343"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC32_SOAP_VoidAuth_Error_Message" time="184.293">
    <error message="Unexpected result for screenshot command: com.google.common.collect.Maps$TransformedEntriesMap instance" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Unexpected result for screenshot command: com.google.common.collect.Maps$TransformedEntriesMap instance
at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:326)
at utilities.CaptureScreenshot.getScreenshot(CaptureScreenshot.java:24)
at Test_Suite.TestHarness_RegressionSuite.TC32_SOAP_VoidAuth_Error_Message(TestHarness_RegressionSuite.java:2843)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC32_SOAP_VoidAuth_Error_Message -->
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC21_HTTP_Validate_for_Void_Auth_Error_Message" time="20.817"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC24_SOAP_TokenAuth_ES_Stripe_Validation" time="38.002"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC08_HTTP_Validate_ES_Stripe_Validation" time="23.035"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC21_HTTP_Validate_for_Void_Auth_Error_Message" time="213.778">
    <error message="Unexpected result for screenshot command: com.google.common.collect.Maps$TransformedEntriesMap instance" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Unexpected result for screenshot command: com.google.common.collect.Maps$TransformedEntriesMap instance
at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:326)
at utilities.CaptureScreenshot.getScreenshot(CaptureScreenshot.java:24)
at Test_Suite.TestHarness_RegressionSuite.TC21_HTTP_Validate_for_Void_Auth_Error_Message(TestHarness_RegressionSuite.java:1883)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC21_HTTP_Validate_for_Void_Auth_Error_Message -->
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC02_HTTP_Tokenise_Request_Response" time="30.355"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC38_HTTP_NonEmbedded_SaveCard_ES_Stripe_Validation" time="32.846"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC11_HTTP_Authorise_Error_Message" time="93.334"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC29_SOAP_TokenAuthSettle_Error_Message" time="30.520"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC35_HTTP_Embedded_SaveCard_ES_Stripe_Validation" time="43.258"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC15_HTTP_Validate_for_Token_Auth_Error_Message" time="25.155"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC07_HTTP_Validate_IFrame" time="17.698"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC18_HTTP_TokenAuthSettle_ES_Stripe_Validation" time="29.473"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC14_HTTP_TokenAuth_ES_Stripe_Validation" time="29.309"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC37_HTTP_NonEmbedded_AuthCapture_ES_Stripe_Validation" time="184.529">
    <error message="Unexpected result for screenshot command: com.google.common.collect.Maps$TransformedEntriesMap instance" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Unexpected result for screenshot command: com.google.common.collect.Maps$TransformedEntriesMap instance
at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:326)
at utilities.CaptureScreenshot.getScreenshot(CaptureScreenshot.java:24)
at Test_Suite.TestHarness_RegressionSuite.TC37_HTTP_NonEmbedded_AuthCapture_ES_Stripe_Validation(TestHarness_RegressionSuite.java:3302)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC37_HTTP_NonEmbedded_AuthCapture_ES_Stripe_Validation -->
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC06_HTTP_Validate_Request_Response" time="24.858"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC28_SOAP_TokenAuthSettle_ES_Stripe_Validation" time="38.339"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC14_HTTP_TokenAuth_ES_Stripe_Validation" time="23.501"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC27_SOAP_TokenSettle_Error_Message_Validation" time="40.663"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC05_HTTP_Tokenise_Error_Message" time="24.251"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC31_SOAP_VoidAuth_ES_Stripe_Validation" time="73.727"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC15_HTTP_Validate_for_Token_Auth_Error_Message" time="23.868"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC32_SOAP_VoidAuth_Error_Message" time="22.291"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC01_HTTP_Probe" time="8.126"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC16_HTTP_TokenSettle_ES_Stripe_Validation" time="26.544"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC37_HTTP_NonEmbedded_AuthCapture_ES_Stripe_Validation" time="35.742"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC19_HTTP_Validate_for_Token_Auth_Settle_Error_Message" time="19.935"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC16_HTTP_TokenSettle_ES_Stripe_Validation" time="21.532"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC22_SOAP_Probe_ES_Stripe_Validation" time="16.327"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC01_HTTP_Probe" time="10.999"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC20_HTTP_VoidAuth_ES_Stripe_Validation" time="26.279"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC24_SOAP_TokenAuth_ES_Stripe_Validation" time="35.551"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC25_SOAP_TokenAuth_Error_Message_Validation" time="38.804"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC39_HTTP_TokenRefund_ES_Stripe_Validation" time="22.292"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC39_HTTP_TokenRefund_ES_Stripe_Validation" time="24.198"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC03_HTTP_Tokenise_IFrame" time="22.597"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC06_HTTP_Validate_Request_Response" time="25.913"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC10_HTTP_Authorise_ES_Stripe_Validation" time="60.453"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC17_HTTP_Validate_for_Token_Settle_Error_Message" time="19.155"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC38_HTTP_NonEmbedded_SaveCard_ES_Stripe_Validation" time="35.775"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC08_HTTP_Validate_ES_Stripe_Validation" time="31.713"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC03_HTTP_Tokenise_IFrame" time="17.229"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC25_SOAP_TokenAuth_Error_Message_Validation" time="36.309"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC29_SOAP_TokenAuthSettle_Error_Message" time="31.283"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC12_HTTP_AuthSettle_ES_Stripe_Validation" time="26.025"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC34_HTTP_Embedded_AuthCapture_ES_Stripe_Validation" time="184.264">
    <error message="Unexpected result for screenshot command: com.google.common.collect.Maps$TransformedEntriesMap instance" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Unexpected result for screenshot command: com.google.common.collect.Maps$TransformedEntriesMap instance
at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:326)
at utilities.CaptureScreenshot.getScreenshot(CaptureScreenshot.java:24)
at Test_Suite.TestHarness_RegressionSuite.TC34_HTTP_Embedded_AuthCapture_ES_Stripe_Validation(TestHarness_RegressionSuite.java:3021)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC34_HTTP_Embedded_AuthCapture_ES_Stripe_Validation -->
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC27_SOAP_TokenSettle_Error_Message_Validation" time="87.462"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC20_HTTP_VoidAuth_ES_Stripe_Validation" time="45.786"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC07_HTTP_Validate_IFrame" time="19.434"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC28_SOAP_TokenAuthSettle_ES_Stripe_Validation" time="128.730"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC09_HTTP_Validate_Error_Message" time="26.388"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC31_SOAP_VoidAuth_ES_Stripe_Validation" time="407.117">
    <error message="Unexpected result for screenshot command: com.google.common.collect.Maps$TransformedEntriesMap instance" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Unexpected result for screenshot command: com.google.common.collect.Maps$TransformedEntriesMap instance
at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:326)
at utilities.CaptureScreenshot.getScreenshot(CaptureScreenshot.java:24)
at Test_Suite.TestHarness_RegressionSuite.TC31_SOAP_VoidAuth_ES_Stripe_Validation(TestHarness_RegressionSuite.java:2757)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC31_SOAP_VoidAuth_ES_Stripe_Validation -->
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC09_HTTP_Validate_Error_Message" time="25.958"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC13_HTTP_AuthSettle_Error_Message" time="57.689"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC18_HTTP_TokenAuthSettle_ES_Stripe_Validation" time="17.646"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC36_HTTP_NonEmbedded_Auth_ES_Stripe_Validation" time="184.180">
    <error message="Unexpected result for screenshot command: com.google.common.collect.Maps$TransformedEntriesMap instance" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Unexpected result for screenshot command: com.google.common.collect.Maps$TransformedEntriesMap instance
at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:326)
at utilities.CaptureScreenshot.getScreenshot(CaptureScreenshot.java:24)
at Test_Suite.TestHarness_RegressionSuite.TC36_HTTP_NonEmbedded_Auth_ES_Stripe_Validation(TestHarness_RegressionSuite.java:3204)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC36_HTTP_NonEmbedded_Auth_ES_Stripe_Validation -->
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC22_SOAP_Probe_ES_Stripe_Validation" time="179.517"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC36_HTTP_NonEmbedded_Auth_ES_Stripe_Validation" time="31.514"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC26_SOAP_TokenSettle_ES_Stripe_Validation" time="38.371"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC26_SOAP_TokenSettle_ES_Stripe_Validation" time="38.197"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC23_SOAP_Probe_Error_Message_Validation" time="17.923"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC34_HTTP_Embedded_AuthCapture_ES_Stripe_Validation" time="46.547"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC04_HTTP_Tokenise_ES_Stripe_Validation" time="24.297"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC33_HTTP_Embedded_Auth_ES_Stripe_Validation" time="47.809"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC05_HTTP_Tokenise_Error_Message" time="33.501"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC23_SOAP_Probe_Error_Message_Validation" time="20.785"/>
  <system-out/>
  <testcase classname="Test_Suite.TestHarness_RegressionSuite" name="TC33_HTTP_Embedded_Auth_ES_Stripe_Validation" time="184.664">
    <error message="Unexpected result for screenshot command: com.google.common.collect.Maps$TransformedEntriesMap instance" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Unexpected result for screenshot command: com.google.common.collect.Maps$TransformedEntriesMap instance
at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:326)
at utilities.CaptureScreenshot.getScreenshot(CaptureScreenshot.java:24)
at Test_Suite.TestHarness_RegressionSuite.TC33_HTTP_Embedded_Auth_ES_Stripe_Validation(TestHarness_RegressionSuite.java:2932)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC33_HTTP_Embedded_Auth_ES_Stripe_Validation -->
  <system-out/>
</testsuite> <!-- Test_Suite.TestHarness_RegressionSuite -->
